name: CI & Version Bump

on:
  pull_request:
    branches: main
  push:
    branches: main
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: 'Version increment (patch, minor, major)'
        options: 
        - patch
        - minor
        - mayor
        required: true
        default: 'patch'


jobs:
  format-lint-type-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # ensure full history for Commitizen
        
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - uses: abatilo/actions-poetry@v3

    - name: Install dependencies
      run: poetry install --no-root --no-interaction

    - name: Format with ruff
      run: poetry run ruff format .

    - name: Lint with ruff
      run: poetry run ruff check .

    - name: Type check with basedpyright
      run: poetry run basedpyright

    - name: Run tests
      env:
        EAPI_PCLOUD_COM_TEST_TOKEN: ${{ secrets.EAPI_PCLOUD_COM_TEST_TOKEN }}
      run: poetry run pytest --tb=short --disable-warnings

    - name: Check conventional commits (branch)
      if: github.ref != 'refs/heads/main'   # only on branch, otherwise origin/main..HEAD is empty
      run: poetry run cz check --rev-range origin/main..HEAD

    - name: Check conventional commits (main)
      if: github.ref == 'refs/heads/main'   # check last commit on main
      run: poetry run cz check --rev-range HEAD~1..HEAD

  bump:
    needs: format-lint-type-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    
    permissions:
      contents: write

    steps:
      - name: Ensure on main branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo "This workflow can only be run on main."
          exit 1

      - name: Validate PAT token}
        run: |
          echo "Checking PAT validity  ..."
          # Make API request to get repo info and response headers
          response=$(curl -s -o /dev/null -w "%{http_code}" -I \
            -H "Authorization: token ${{ secrets.PAT }}" \
            https://api.github.com/repos/${{ github.repository }})

          if [ "$response" -ne 200 ]; then
            echo "::error::PAT token check failed: HTTP status $response"
            echo "::error::Token might be expired, invalid, or missing permissions."
            exit 1
          fi
          echo "PAT token is valid and has required scopes."

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure full history for Commitizen

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Set Git auth to use PAT
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.co"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}

      - name: Run Commitizen bump and generate changelog
        run: |
          poetry run cz bump --yes --increment ${{ github.event.inputs.increment }} --changelog
          git push origin HEAD:main
          git push origin --tag