name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  format-lint-type-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # ensure full history for Commitizen
        
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - uses: abatilo/actions-poetry@v3

    - name: Install dependencies
      run: poetry install --no-root --no-interaction

    - name: Format with ruff
      run: poetry run ruff format .

    - name: Lint with ruff
      run: poetry run ruff check .

    - name: Type check with basedpyright
      run: poetry run basedpyright

    - name: Run tests
      env:
        EAPI_PCLOUD_COM_TEST_TOKEN: ${{ secrets.EAPI_PCLOUD_COM_TEST_TOKEN }}
      run: poetry run pytest --tb=short --disable-warnings

    - name: Check conventional commits
      if: github.ref != 'refs/heads/main'
      run: poetry run cz check --rev-range origin/main..HEAD
